SET FOREIGN_KEY_CHECKS=0;
DROP TABLE IF EXISTS `fx_room_source`;
CREATE TABLE `fx_room_source` (
  `id` int(11) unsigned NOT NULL AUTO_INCREMENT COMMENT '主键ID',
  `parent_id` varchar(50) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '房源的所属,形式为：公司id-楼盘id-楼宇id-房间id',
  `hm_id` int(11) unsigned NOT NULL COMMENT '房间id',
  `type` tinyint(1) unsigned NOT NULL DEFAULT '1' COMMENT '类型 1-纯住宅 2-纯办公 3-住宅改办公 默认为1',
  `room_type` tinyint(2) DEFAULT '1' COMMENT '户型 1-一室 2-二室 3-三室 4-四室 5-四室以上 99-其它',
  `furnish_type` tinyint(2) DEFAULT '2' COMMENT '装修 1-毛坯 2-简装 3-精装 4-豪装 99-其它',
  `follow_type` tinyint(1) DEFAULT '1' COMMENT '跟进方式 1-普通 2-重点 3-放弃',
  `status` tinyint(1) DEFAULT '1' COMMENT '状态 1-待租，未签约 2-已租，已签约 3-终止托管',
  `cm_id` int(11) DEFAULT NULL COMMENT '公司id',
  `start_time` datetime NOT NULL COMMENT '托管开始时间',
  `sign_time` datetime NOT NULL COMMENT '托管登记时间',
  `end_time` datetime NOT NULL COMMENT '托管结束时间',
  `limit` int(11) NOT NULL DEFAULT '1' COMMENT '托管期限(以月为单位)',
  `trustee_fee` float(11,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '托管价格（元/月）',
  `total_trustee_fee` float(11,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '总托管费',
  `deposit` float(11,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '押金',
  `rent` float(11,2) unsigned NOT NULL DEFAULT '0.00' COMMENT '租金 元/月',
  `furniture` varchar(60) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '配套设施(ids，以逗号隔开)',
  `is_increase` tinyint(1) DEFAULT '-1' COMMENT '是否递增 1:是  -1:否',
  `increase_type` tinyint(1) unsigned DEFAULT '1' COMMENT '递增类型 1:定额 2:百分比',
  `increase_price` float(11,2) DEFAULT NULL COMMENT '递增金额(每期)',
  `increasing_cycle` int(11) DEFAULT NULL COMMENT '递增周期(以月为单位)',
  `uid` int(11) unsigned DEFAULT NULL COMMENT '录入用户id',
  `remark` varchar(300) COLLATE utf8_unicode_ci DEFAULT NULL COMMENT '备注',
  `update_time` datetime DEFAULT NULL COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `parent_id` (`parent_id`) USING BTREE COMMENT '房源所属ID',
  KEY `hm_id` (`hm_id`) USING BTREE COMMENT '房间ID',
  KEY `status` (`status`) USING BTREE COMMENT '状态',
  KEY `cm_id` (`cm_id`) USING BTREE COMMENT '企业ID',
  KEY `type` (`type`) USING BTREE COMMENT '类型',
  KEY `room_type` (`room_type`) USING BTREE COMMENT '户型',
  KEY `furnish_type` (`furnish_type`) USING BTREE COMMENT '装修'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci ROW_FORMAT=COMPACT;
